namespace Runtime.Definition
{
    public enum ButtonType
    {
        Other = -1,
        MainMenu = 0,
        Quest = 1,
        Shop = 2,
        Storage = 3,
        Setting = 4,
        Map = 5,
        NewChar = 6,
        CharPackage = 7,
        DailyQuest = 8,
        AddMoreGold = 9,
        AddMoreGem = 10,
        Challenge = 11,
        Achievement = 12,
        Gift = 13,
        HeroManagerment = 14,
        SelectHero = 15,
        Camping = 16,
        Packgage = 17,
        Diamond = 18,
        Resource = 19,
        Back = 20,
        Daily = 21,
        Weekly = 22,
        View = 23,
        Language = 24,
        Youtube = 25,
        Facebook = 26,
        Instagram = 27,
        Sound = 28,
        Music = 29,
        BattlePass = 30,
        Teleport = 31,
        BetaBuff = 32,

        Gacha = 30,
        Hero = 31,
        Headquarter = 32,
        Build = 33,
        Battle = 34,
        Mail = 35,
        RePosition = 36,
        Profile = 37,
        PlayGameSplashArt = 39,
        PlayStage = 40,
        ReplayInStage = 41,
        NextStage = 42,
        Ok = 43,
        Yes = 44,
        Confirm = 45,
        Continue = 46,
        Cancel = 47,
        Close = 48,
        No = 49,
        Upgrade = 50,
        GachaBasicX1 = 51,
        GachaBasicX10 = 52,
        GachaPremiumX1 = 53,
        GachaPremiumX10 = 54,
        Pause = 55,

        StarterPack = 56,
        FirstPurchase = 57,
        Stamina = 58,
        Gem = 59,
        Gold = 60,
        HomeInStage = 61,
        Quit = 62,
        Replay = 63,
        Home = 64,
        PiggyBank = 65,

        MenuBar = 66,
        Settings = 67,
        Accounts = 68,
        MainQuest = 69,
        DailyFortune = 70,
        ChangeGameControl = 71,

        ResourceShop = 72,
        CampaignPass = 73,
        ResourceBundles = 74,
        CustomizeBundles = 75,
        
        Recruit = 76,
        GiveUpGacha = 77,
        OpenPopupRefreshGacha = 78,
        Reroll = 79,
        FlashSale = 80,
        GrowPack = 81,
        PremiumCampInfo = 82,

        Unidentified = 9999,
    }
}