namespace Runtime.Definition
{
    public enum ResourceType
    {
        Gold = 0,
        Gem = 1,
        Wood = 2,
        Food = 3,
        GreenCrystal = 4,
        RedCrystal = 5,
        VioletCrystal = 6,
        BattlePassExp = 7,
        DailyQuestExp = 8,
        WeeklyQuestExp = 9,
        HeroFragment = 10,
        PlayerExp = 11,
        TicketRefresh = 12,
        KeyCage = 13,
        PieceOfLight = 14,
        Equipment = 15,
        BasicMaterial = 16,
        AdvanceMaterial = 17,
        LavaLakeScrollRare = 18,
        GlacierCaveScrollRare = 19,
        LostCityScrollRare = 20,
        IllusionDesertScrollRare = 21,
        DarkCastleScrollRare = 22,
        LavaLakeScrollEpic = 23,
        GlacierCaveScrollEpic = 24,
        LostCityScrollEpic = 25,
        IllusionDesertScrollEpic = 26,
        DarkCastleScrollEpic = 27,
        LavaLakeScrollLegend = 28,
        GlacierCaveScrollLegend = 29,
        LostCityScrollLegend = 30,
        IllusionDesertScrollLegend = 31,
        DarkCastleScrollLegend = 32,
    }
}   