namespace Runtime.Definition
{
    public enum SkillType
    {
        None,

        // Boss.
        RushAttack = 101,
        SpawnFlail = 102,
        ChiwiStrike = 103,
        SwampKingFirst = 104,
        SwampKingSecond = 105,
        SpawnDarkFlail = 106,
        MultiPaw = 107,
        DeathClaws = 108,
        Swing = 109,
        EarthShake = 110,
        GoldenMimicFirst = 111,
        GoldenMimicSecond = 112,
        Smash = 113,
        Collapse = 114,
        SnowBall = 115,
        IceSplitter = 116,
        FireBall = 117,
        EndOfAnEra = 118,

        // Hero.
        HeavyStrike = 3,
        Encourage = 4,
        Carpenter = 5,
        AxeStrike = 6,
        TreasureHunter = 7,
        StrongBody = 8,
        HealingHand = 9,
        SharedKnowledge = 10,
        WhirlStrike = 11,
        WindStep = 12,
        PikeThrust = 13,
        ArmyTraining = 14,
        MultiShot = 15,
        SteadyAim = 16,
        Enrage = 17,
        CallOfTheMoon = 18,
        HealingOrb = 19,
        NatureBlessing = 20,
        FireBurst = 21,
        HeadShot = 22,
        FireBlast = 23,
        ScorchedEarth = 24,

        LightningBolt = 25,
        BatSwarm = 26,
        BattleEndure = 27,
        BloodyNightmare = 28,
        BraveHeart = 29,
        Cleave = 30,
        Cyclone = 31,
        DarkBall = 32,
        DarkBarrage = 33,
        FlurryOfKnives = 34,
        GoddessAura = 35,
        GroundSlam = 36,
        HammerSlam = 37,
        HealingMagic = 38,
        KitsuneBless = 39,
        KitsuneReincarnation = 40,
        LightningHuge = 41,
        MysticSpell = 42,
        PandemicEnd = 43,
        PoisonousFlask = 44,
        PowerShot = 45,
        Pray = 46,
        Provoke = 47,
        PunishmentLight = 48,
        Purification = 49,
        RainOfArrow = 50,
        ShurikenThrow = 51,
        SmokeBomb = 52,
        SpearThrow = 53,
        WeaknessStrike = 54,
        SwipeKick = 55,
        Slam = 56,
        BurningStrike = 57,
        FocusDefense = 58,
        Madness = 59,
        Frenzy = 60,
    }
}