namespace Runtime.Definition
{
    public enum StatusEffectType
    {
        None = 0,
        Stun = 1,
        BleedAttack = 3,
        Heal = 4,
        Regen = 5,
        Dread = 6,
        Haste = 7,
        Quick = 8,
        HealAttack = 9,
        Hardened = 10,
        Pull = 14,
        Root = 15,
        Freeze = 17,
        KnockUp = 20,
        PoisonAttack = 21,
        CritChanceBuff = 22,
        EvasionBuff = 23,
        AttackBuff = 24,
        BurnAttack = 25,
        Chill = 26,
        FixedDamageReductionBuff = 27,
        DamageReductionBuff = 28,
        NegativeStatusEffectRemove = 29,
        Slow = 30,
        HealingAttackDuration = 31,
        DamageReductionNonDuration = 32,
        Taunt = 33,
        FixedDamageReductionNonDuration = 34,
        Berserker = 35,
    }
}